name: MERN Deploy Pipeline
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Server Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/mern-server ./server

      - name: Push Server Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/mern-server

      - name: Build Client Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/mern-client ./client

      - name: Push Client Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/mern-client